// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ola.Data;

#nullable disable

namespace ola.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251218232020_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin-001",
                            ConcurrencyStamp = "role-admin-001",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-user-001",
                            ConcurrencyStamp = "role-user-001",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "demo-user-123",
                            RoleId = "role-admin-001"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ola.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "demo-user-123",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e5111310-467c-411f-97a4-04e1cc90f576",
                            Email = "demo@example.com",
                            EmailConfirmed = true,
                            FirstName = "Demo",
                            FullName = "Demo User",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "DEMO@EXAMPLE.COM",
                            NormalizedUserName = "DEMO@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ1dUZ5EONosFVJeFt3PcTJS3BM4tiTqcKoy0eZZ+j9RnBbTK1Z4VHKakiobP6KyIw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "27fe6a53-3d2e-4360-99d7-634cac1c6f21",
                            TwoFactorEnabled = false,
                            UserName = "demo@example.com"
                        });
                });

            modelBuilder.Entity("ola.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("ola.Models.DailyProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("HabitId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.HasIndex("UserId", "HabitId", "Date");

                    b.ToTable("DailyProgresses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 1,
                            UserId = "demo-user-123",
                            Value = 80
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 1,
                            UserId = "demo-user-123",
                            Value = 100
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 1,
                            UserId = "demo-user-123",
                            Value = 75
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 2,
                            UserId = "demo-user-123",
                            Value = 100
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 2,
                            UserId = "demo-user-123",
                            Value = 90
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 3,
                            UserId = "demo-user-123",
                            Value = 100
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2024, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 3,
                            UserId = "demo-user-123",
                            Value = 100
                        });
                });

            modelBuilder.Entity("ola.Models.EmotionEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Anger")
                        .HasColumnType("int");

                    b.Property<int?>("Anxiety")
                        .HasColumnType("int");

                    b.Property<int?>("Boredom")
                        .HasColumnType("int");

                    b.Property<int?>("Calmness")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emotion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Intensity")
                        .HasColumnType("int");

                    b.Property<int?>("Joy")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("EmotionEntries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anger = 1,
                            Anxiety = 4,
                            Boredom = 2,
                            Calmness = 2,
                            CreatedAt = new DateTime(2024, 12, 10, 10, 30, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2024, 12, 10, 10, 30, 0, 0, DateTimeKind.Utc),
                            Joy = 2,
                            Text = "Feeling anxious but trying to stay calm.",
                            UserId = "demo-user-123"
                        },
                        new
                        {
                            Id = 2,
                            Anger = 1,
                            Anxiety = 1,
                            Boredom = 1,
                            Calmness = 4,
                            CreatedAt = new DateTime(2024, 12, 11, 14, 15, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2024, 12, 11, 14, 15, 0, 0, DateTimeKind.Utc),
                            Joy = 5,
                            Text = "Very productive day, lots of joy.",
                            UserId = "demo-user-123"
                        },
                        new
                        {
                            Id = 3,
                            Anger = 1,
                            Anxiety = 2,
                            Boredom = 4,
                            Calmness = 3,
                            CreatedAt = new DateTime(2024, 12, 12, 16, 45, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2024, 12, 12, 16, 45, 0, 0, DateTimeKind.Utc),
                            Joy = 2,
                            Text = "A bit bored and low energy.",
                            UserId = "demo-user-123"
                        });
                });

            modelBuilder.Entity("ola.Models.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WhyReason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status", "Priority");

                    b.ToTable("Goals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete C# fundamentals and build a working application",
                            Priority = 2,
                            ProgressPercentage = 40,
                            Status = 1,
                            Title = "Learn C#",
                            UpdatedAt = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "demo-user-123",
                            WhyReason = ""
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Practice mindfulness and maintain emotional well-being",
                            Priority = 2,
                            ProgressPercentage = 70,
                            Status = 1,
                            Title = "Improve Mental Health",
                            UpdatedAt = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "demo-user-123",
                            WhyReason = ""
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Maintain a consistent exercise routine with 3 sessions per week",
                            Priority = 1,
                            ProgressPercentage = 20,
                            Status = 1,
                            Title = "Exercise 3x Weekly",
                            UpdatedAt = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "demo-user-123",
                            WhyReason = ""
                        });
                });

            modelBuilder.Entity("ola.Models.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("Habits", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Drink 8 glasses of water daily",
                            Name = "Drink Water",
                            UserId = "demo-user-123"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read for at least 20 minutes every day",
                            Name = "Read 20 Minutes",
                            UserId = "demo-user-123"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Start the day with 10 minutes of stretching",
                            Name = "Morning Stretching",
                            UserId = "demo-user-123"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ola.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ola.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ola.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ola.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ola.Models.AuditLog", b =>
                {
                    b.HasOne("ola.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ola.Models.DailyProgress", b =>
                {
                    b.HasOne("ola.Models.Habit", "Habit")
                        .WithMany("DailyProgresses")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ola.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Habit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ola.Models.EmotionEntry", b =>
                {
                    b.HasOne("ola.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ola.Models.Goal", b =>
                {
                    b.HasOne("ola.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ola.Models.Habit", b =>
                {
                    b.HasOne("ola.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ola.Models.Habit", b =>
                {
                    b.Navigation("DailyProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
